project_id = "ssjoetiitctqzapymtzl"

[functions.angel-chat]
verify_jwt = false

[functions.analyze-onboarding]
verify_jwt = false

[functions.analyze-reward-question]
verify_jwt = false

[functions.analyze-reward-journal]
verify_jwt = false

[functions.check-user-energy]
verify_jwt = false

[functions.send-healing-message]
verify_jwt = false

[functions.process-engagement-reward]
verify_jwt = false

[functions.suspend-user]
verify_jwt = true

[functions.fetch-google-content]
verify_jwt = false
